default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gym(task: "test")
  end

  desc "New Beta Build to HockeyApp"
  lane :beta do
    gym(task: "assemble", build_type: "release")
    hockey(
      api_token: "bb63768f191246f9bd7a2ba8dc0e1c6e",
      #apk: "/Users/paul.hoess/jenkins_haus/workspace/app.android.fastlane.deploy.beta/app/build/outputs/apk/release/app-release-unsigned.apk",
      release_type: "0",
      repository_url: "ssh://git@git.aldi-international.com:45481/atp2/ahead-ci-mobile.git",
      build_server_url: "https://192.168.99.100"
    )
